### ISSUE TITLE
get_gitid returns "FileNotFoundError"

### ISSUE THREAD

**Issue by feschmidt** [steelelab-delft/stlab#33]
On the Triton PC, `get_gitid` has issues with the directory name. It seems like the directory string is not split correctly:

> `Traceback (most recent call last):
  File "D:\measurement_data_triton\Jasper\B=0.256e-3\sweep_pumppow_pumpfreq_VNApow.py", line 115, in <module>
    myfile1 = stlab.newfile('Pump_on', str(tag2), data1.keys(), mypath= VNApowpath, autoindex=True)#Open file in for loop so labels are set automatically
  File "c:\libs\stlab\utils\newfile.py", line 138, in newfile
    getgitid.get_gitid(myfile)
  File "c:\libs\stlab\utils\getgitid.py", line 43, in get_gitid
    with open(dirname + '.stlab_id.txt', 'a') as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\measurement_data_triton\\Jasper\\B=0.256e-3\\p_pow-79.48dB\\p_freq7.305GHz\\VNA_pow-145--110dB\\Pump_on1_2019_04_12_10.53.55_pp_-79.48_pfr_7.305_VNA_-145.0\\D:\\measurement_data_triton\\Jasper\\B=0.256e-3\\p_pow-79.48dB\\p_freq7.305GHz\\VNA_pow-145--110dB\\Pump_on1_2019_04_12_10.53.55_pp_-79.48_pfr_7.305_VNA_-145.0.stlab_id.txt'`

**Comment by feschmidt** [comment]
for now, possible workaround is to set `git_id=False` in `stlab.newfile`

**Comment by feschmidt** [comment]
Using pwd might be useful here

**Comment by feschmidt** [comment]
fixed in [`35eb5bd`](https://github.com/steelelab-delft/stlab/commit/35eb5bdecf9ae6110f4faeea5e4619ed9b96f75b)
